name: rideshare_app
description: Full advanced RideShare Flutter starter
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  firebase_messaging: any
  provider: any

flutter:
  uses-material-design: true
  assets:
    - assets/
