name: rideshareApp
description: Full advanced RideShare Flutter starter
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  # firebase_messaging: any
  provider: any
  intl: ^0.19.0
  lottie: ^3.0.0
  http: ^1.1.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  firebase_app_check: ^0.2.1
  image_picker: ^1.1.1
  app_links: ^5.0.0
  image_cropper: ^8.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/
